### ISSUE TITLE
Test Ontop performance vs Blazegraph

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-CDS/DataFAIRifier#12]
Although we have defined R2RML mappings, we need to test the performance of Ontop in comparison to constructing all triples. Is there a performance gain/reduction?

**Comment by bpmweel** [comment]
We discussed the following:

- We can use shape expressions to describe the desired output graph
- This can then be used as a gold standard to validate ontop and other reasoning methods
- MyShapeExpressionTest is a tool that can validate using shape expressions
- We hope to use a dataset of rougly 3000 patients.
- A mapping for this dataset will need to be constructed.

We will also test the performance of
- Ontop
- Blazegraph
- Perhaps virtuoso?

**Comment by MartineDeVos** [comment]
We decided to evaluate the following:
1.Performance, i.e., resource footprint and time 
2.Quality of query results, i.e., precision and recall compared to gold standard

I think shape expressions are not suitable as gold standard in our project (see wiki: evaluation set up). We may need to create our own benchmark together with medical experts.

**Comment by jvsoest** [comment]
Blazegraph isn't further developed anymore
